name: JAR with Dependencies Development Build

on:
  push:
    branches:
      - develop

jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify


  build-to-fat-jar:
    needs: verify
    name: Build on ${{ matrix.os.name }} to fat jar
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, file-mod: "linux" },
          { name: windows-latest, file-mod: "win" }
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Prepare project
        run: |
          rm src/main/java/module-info.java

      - name: Build with Maven
        run: |
          mvn -P fat-jar --batch-mode --update-snapshots clean install package

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/noel.jar
          asset_name: noel-${{ matrix.os.file-mod }}.jar
          overwrite: true
          tag: dev-jar
          prerelease: true
          release_name: jar with dependencies
